name:                parlay-calculator-api
version:             0.1.0.0
github:              "tlentz"
license:             BSD3
author:              "Tyler Lentz"
maintainer:          "tyler.cg.lentz@gmail.com"
copyright:           "2019 Tyler Lentz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sim-space#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- servant

library:
  source-dirs: src

executables:
  parlay-calculator-api:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parlay-calculator-api

tests:
  parlay-calculator-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parlay-calculator-api